// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mojylvirtkkgmwbwgocl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vanlsdmlydGtrZ213Yndnb2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODI5MzgsImV4cCI6MjA1NTI1ODkzOH0.ieOjMwQoZMyEdeivSSiEda34gYbHzSDxaSI0QBI9w_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);